name: messenger_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-91.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.3
  equatable: ^2.0.5
  auto_route: ^7.8.4
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  cloud_firestore: ^4.9.3
  flutter_localizations:
    sdk: flutter 
  intl: any
  intl_utils: ^2.8.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy.ttf
flutter_intl:
  enabled: true
